name: fridge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # flutter_barcode_scanner: ^2.0.0
  mobile_scanner: ^6.0.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  http: ^1.2.2
  shared_preferences: ^2.3.4
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  analyzer: ^4.7.0

flutter:
  uses-material-design: true
